<?php
namespace Database\Seeders;



use Illuminate\Database\Seeder;
use App\Models\quizzes;

class GeneralQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'question' => 'What is the capital of France?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Paris',
                'option_b' => 'London',
                'option_c' => 'Berlin',
                'option_d' => 'Rome',
                'answer' => 'Paris',
            ],
            [
                'question' => 'Which planet is known as the Red Planet?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Mars',
                'option_b' => 'Venus',
                'option_c' => 'Jupiter',
                'option_d' => 'Mercury',
                'answer' => 'Mars',
            ],
            [
                'question' => 'What is the symbol for the chemical element Iron?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Fe',
                'option_b' => 'C',
                'option_c' => 'Na',
                'option_d' => 'Au',
                'answer' => 'Fe',
            ],
            [
                'question' => 'Which year did World War II end?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => '1945',
                'option_b' => '1918',
                'option_c' => '1939',
                'option_d' => '1941',
                'answer' => '1945',
            ],
            [
                'question' => 'Who painted the Mona Lisa?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Leonardo da Vinci',
                'option_b' => 'Pablo Picasso',
                'option_c' => 'Vincent van Gogh',
                'option_d' => 'Michelangelo',
                'answer' => 'Leonardo da Vinci',
            ],
            [
                'question' => 'What is the largest ocean in the world?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Pacific Ocean',
                'option_b' => 'Atlantic Ocean',
                'option_c' => 'Indian Ocean',
                'option_d' => 'Arctic Ocean',
                'answer' => 'Pacific Ocean',
            ],
            [
                'question' => 'Who is the author of "To Kill a Mockingbird"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Harper Lee',
                'option_b' => 'F. Scott Fitzgerald',
                'option_c' => 'Ernest Hemingway',
                'option_d' => 'Mark Twain',
                'answer' => 'Harper Lee',
            ],
            [
                'question' => 'Which country won the FIFA World Cup in 2018?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'France',
                'option_b' => 'Germany',
                'option_c' => 'Brazil',
                'option_d' => 'Spain',
                'answer' => 'France',
            ],
            [
                'question' => 'What is the chemical symbol for gold?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Au',
                'option_b' => 'Ag',
                'option_c' => 'Cu',
                'option_d' => 'Pt',
                'answer' => 'Au',
            ],
            [
                'question' => 'In which year did the Titanic sink?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => '1912',
                'option_b' => '1905',
                'option_c' => '1920',
                'option_d' => '1918',
                'answer' => '1912',
            ],
            [
                'question' => 'Who wrote the play "Romeo and Juliet"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'William Shakespeare',
                'option_b' => 'Arthur Miller',
                'option_c' => 'Tennessee Williams',
                'option_d' => 'Anton Chekhov',
                'answer' => 'William Shakespeare',
            ],
            [
                'question' => 'Which animal is known as the "king of the jungle"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Lion',
                'option_b' => 'Tiger',
                'option_c' => 'Elephant',
                'option_d' => 'Giraffe',
                'answer' => 'Lion',
            ],
            [
                'question' => 'What is the largest planet in our solar system?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Jupiter',
                'option_b' => 'Saturn',
                'option_c' => 'Neptune',
                'option_d' => 'Earth',
                'answer' => 'Jupiter',
            ],
            [
                'question' => 'Which country hosted the 2016 Summer Olympics?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Brazil',
                'option_b' => 'Russia',
                'option_c' => 'China',
                'option_d' => 'United States',
                'answer' => 'Brazil',
            ],
            [
                'question' => 'Who is the current CEO of Tesla Motors?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Elon Musk',
                'option_b' => 'Jeff Bezos',
                'option_c' => 'Tim Cook',
                'option_d' => 'Bill Gates',
                'answer' => 'Elon Musk',
            ],
            [
                'question' => 'What is the largest continent by land area?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Asia',
                'option_b' => 'Africa',
                'option_c' => 'North America',
                'option_d' => 'South America',
                'answer' => 'Asia',
            ],
            [
                'question' => 'Who painted the famous artwork "The Starry Night"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Vincent van Gogh',
                'option_b' => 'Leonardo da Vinci',
                'option_c' => 'Pablo Picasso',
                'option_d' => 'Claude Monet',
                'answer' => 'Vincent van Gogh',
            ],
            [
                'question' => 'Which country is famous for the Taj Mahal?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'India',
                'option_b' => 'China',
                'option_c' => 'Japan',
                'option_d' => 'Egypt',
                'answer' => 'India',
            ],
            [
                'question' => 'What is the largest animal on Earth?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Blue whale',
                'option_b' => 'Elephant',
                'option_c' => 'Giraffe',
                'option_d' => 'Hippopotamus',
                'answer' => 'Blue whale',
            ],
            [
                'question' => 'Who is the current Prime Minister of Canada?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Justin Trudeau',
                'option_b' => 'Stephen Harper',
                'option_c' => 'Andrew Scheer',
                'option_d' => 'Jagmeet Singh',
                'answer' => 'Justin Trudeau',
            ],
            [
                'question' => 'Which country is known as the "Land of the Rising Sun"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Japan',
                'option_b' => 'China',
                'option_c' => 'South Korea',
                'option_d' => 'Vietnam',
                'answer' => 'Japan',
            ],
            [
                'question' => 'Who is the author of the Harry Potter book series?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'J.K. Rowling',
                'option_b' => 'Stephenie Meyer',
                'option_c' => 'George R.R. Martin',
                'option_d' => 'Dan Brown',
                'answer' => 'J.K. Rowling',
            ],
            [
                'question' => 'Which city hosted the 2012 Summer Olympics?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'London',
                'option_b' => 'Beijing',
                'option_c' => 'Rio de Janeiro',
                'option_d' => 'Sydney',
                'answer' => 'London',
            ],
            [
                'question' => 'What is the largest desert in the world?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Sahara Desert',
                'option_b' => 'Arabian Desert',
                'option_c' => 'Gobi Desert',
                'option_d' => 'Kalahari Desert',
                'answer' => 'Sahara Desert',
            ],
            [
                'question' => 'Who discovered gravity?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Isaac Newton',
                'option_b' => 'Albert Einstein',
                'option_c' => 'Galileo Galilei',
                'option_d' => 'Nikola Tesla',
                'answer' => 'Isaac Newton',
            ],
            [
                'question' => 'Which city is known as the "Eternal City"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Rome',
                'option_b' => 'Athens',
                'option_c' => 'Cairo',
                'option_d' => 'Paris',
                'answer' => 'Rome',
            ],
            [
                'question' => 'Who is the main protagonist in "The Lord of the Rings"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Frodo Baggins',
                'option_b' => 'Gandalf',
                'option_c' => 'Aragorn',
                'option_d' => 'Samwise Gamgee',
                'answer' => 'Frodo Baggins',
            ],
            [
                'question' => 'What is the largest waterfall in the world?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Angel Falls',
                'option_b' => 'Niagara Falls',
                'option_c' => 'Victoria Falls',
                'option_d' => 'Iguazu Falls',
                'answer' => 'Angel Falls',
            ],
            [
                'question' => 'Which country is home to the Great Barrier Reef?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Australia',
                'option_b' => 'New Zealand',
                'option_c' => 'Maldives',
                'option_d' => 'Philippines',
                'answer' => 'Australia',
            ],
            [
                'question' => 'What is the largest bird in the world?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Ostrich',
                'option_b' => 'Emu',
                'option_c' => 'Albatross',
                'option_d' => 'Eagle',
                'answer' => 'Ostrich',
            ],
            [
                'question' => 'Who wrote the novel "Pride and Prejudice"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Jane Austen',
                'option_b' => 'Emily Bronte',
                'option_c' => 'Charlotte Bronte',
                'option_d' => 'Virginia Woolf',
                'answer' => 'Jane Austen',
            ],
            [
                'question' => 'Which country is known as the "Land of Fire and Ice"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Iceland',
                'option_b' => 'Greenland',
                'option_c' => 'Norway',
                'option_d' => 'Finland',
                'answer' => 'Iceland',
            ],
            [
                'question' => 'What is the largest tree species in the world?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'Sequoia',
                'option_b' => 'Redwood',
                'option_c' => 'Baobab',
                'option_d' => 'Oak',
                'answer' => 'Sequoia',
            ],
            [
                'question' => 'Who is the author of "The Great Gatsby"?',
                'category' => 'general',
                'type' => 'multiple_choice',
                'option_a' => 'F. Scott Fitzgerald',
                'option_b' => 'Ernest Hemingway',
                'option_c' => 'Mark Twain',
                'option_d' => 'Harper Lee',
                'answer' => 'F. Scott Fitzgerald',
            ],
        ];
        foreach ($questions as $question) {
            Quizzes::create($question);
        }
    }
}